spring:
    profiles:
        active: dev
    application:
        name: artist-stalker-bot-client-app-for-java
    autoconfigure:
        exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  